services:
  caddy:
    image: livekit/caddyl4
    command: run --config /etc/caddy.yaml --adapter yaml
    restart: unless-stopped
    #ports:
    #  - "80:80/tcp"
    #  - "443:443/tcp"
    volumes:
      - ./caddy.yaml:/etc/caddy.yaml
      - ./caddy_data:/data

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - "7881:7881/tcp"
      - "3478:3478/udp"
      - "50000-60000:50000-60000/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    labels:
      - traefik.enable=true
      - "traefik.http.routers.livekit.rule=Host(`livekit.uptopoint.com`)"
      - traefik.http.routers.livekit.entrypoints=https

  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    ports:
      - "6379:6379/tcp"
    volumes:
      - ./redis.conf:/etc/redis.conf
